export const sampleData = [
  {
    title: "The Silent Horizon",
    description: "A journey across forgotten lands.",
    duration: 120,
    genre: "Adventure",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BN2VhNjk5NDItYmM0Ny00ZTFiLTg3NGYtY2Y3ZjgzNjQ1NjA5XkEyXkFqcGc@._V1_.jpg",
    pricing: { standard: 5.99, VIP: 12.99 },
    releaseDate: "2025-02-15",
    classification: "PG-13",
  },
  {
    title: "Neon Streets",
    description: "A cyberpunk detective mystery.",
    duration: 140,
    genre: "Sci-Fi",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BY2ViNGI1YjktNjc4ZS00MTAyLWIwZTItMTk2YzFkMzFhNjQxXkEyXkFqcGc@._V1_.jpg",
    pricing: { standard: 6.99, VIP: 13.99 },
    releaseDate: "2025-04-01",
    classification: "R",
  },
  {
    title: "Moonlight Sonata",
    description: "A heartwarming drama about family and music.",
    duration: 110,
    genre: "Drama",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZjdkYTQ3YTAtMTcwZS00ZmRhLWFjNTAtMTE3YmQ3ODkzYjE0XkEyXkFqcGc@._V1_.jpg",
    pricing: { standard: 4.99, VIP: 10.99 },
    releaseDate: "2025-01-05",
    classification: "PG",
  },
  {
    title: "Last Stand",
    description: "A gripping war story of courage and sacrifice.",
    duration: 150,
    genre: "Action",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMmI3ZDQyN2EtZjQ0MC00YzI5LTkzYTUtNzVlMDA4ZGVjODBlXkEyXkFqcGc@._V1_.jpg",
    pricing: { standard: 7.99, VIP: 15.99 },
    releaseDate: "2025-03-20",
    classification: "R",
  },
  {
    title: "Whispers in the Dark",
    description: "A chilling tale of a haunted town.",
    duration: 105,
    genre: "Horror",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMzI1ZjFiNjUtNTQzMC00NzAwLTgxNGItZTVmNTFjYzg4MjY3XkEyXkFqcGc@._V1_.jpg",
    pricing: { standard: 5.49, VIP: 11.49 },
    releaseDate: "2025-10-31",
    classification: "PG-13",
  },
  {
    title: "Galactic Voyage",
    description: "Explorers journey beyond the known galaxy.",
    duration: 135,
    genre: "Sci-Fi",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BM2NhODdhNmUtMzNkNi00ZjhjLThlNGEtNjFjZWY0YzRlYjRlXkEyXkFqcGc@._V1_.jpg",
    pricing: { standard: 6.49, VIP: 13.49 },
    releaseDate: "2025-06-12",
    classification: "PG",
  },
  {
    title: "The Hidden Truth",
    description: "A journalist uncovers a shocking conspiracy.",
    duration: 125,
    genre: "Thriller",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMGEwZmQ5MjctMGRkMC00OTlkLTk5ZjgtYzQ1ODQzYmYyNjgzXkEyXkFqcGc@._V1_.jpg",
    pricing: { standard: 5.99, VIP: 11.99 },
    releaseDate: "2025-05-03",
    classification: "PG-13",
  },
  {
    title: "Rise of the Phoenix",
    description: "A fantasy epic of magic and destiny.",
    duration: 160,
    genre: "Fantasy",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYTFlMGE4YjUtOTM0OS00YmNiLTk4MmQtMTE2MzBiOTljNjA2XkEyXkFqcGc@._V1_.jpg",
    pricing: { standard: 7.49, VIP: 14.99 },
    releaseDate: "2025-07-21",
    classification: "PG-13",
  },
  {
    title: "Echoes of Yesterday",
    description: "A nostalgic romance about love and time.",
    duration: 115,
    genre: "Romance",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZGE2NGM0YjEtNzliNy00ZTk1LThlZTEtNTM1ZDU5MGRjYjY4XkEyXkFqcGc@._V1_.jpg",
    pricing: { standard: 4.99, VIP: 9.99 },
    releaseDate: "2025-02-28",
    classification: "PG",
  },
  {
    title: "Game Over",
    description: "Gamers trapped in a deadly virtual reality.",
    duration: 130,
    genre: "Action/Sci-Fi",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjQ2MTAwNTI5NV5BMl5BanBnXkFtZTgwNjI3NzY3MDE@._V1_.jpg",
    pricing: { standard: 6.99, VIP: 13.99 },
    releaseDate: "2025-08-10",
    classification: "R",
  },
];
